### ISSUE TITLE
Syntax colouring is completely disabled after latest update.

### ISSUE THREAD

**Issue by Hazzard13** [thierryc/dark-side-of-the-moon-syntax#1]
Not sure what's happened here, but after yesterday's update, all text in atom is just white. My grammer is correctly set, and even invisibles are showing as plain white text.

Love the syntax theme btw, I'm dying to have my favourite colour scheme back.

**Comment by thierryc** [comment]
do you update Atom ? 

```
apm -version
```

What do you get when you enter apm -version in terminal ? 

0.6.0 is for the last  Atom 1.13.
Stop using shadow DOM selectors.

**Comment by Hazzard13** [comment]
Hm. I update everything as soon as possible, but it seems to be working now. Either I got the update or v.0.67 fixed the issue. Whatever the case, thanks so much for the quick response! I'm relieved to have my normal colours back.
